plugin:
  # Warmuptime in seconds
  warmuptime: 2
#Disabled worlds for /back
  disabled-worlds: []
  
##########################################
##############Database module#############
##########################################

  # MySQL-connection for homes.
sql:
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  debugmode: false

