name: MineSuiteCore
main : de.linzn.mineSuite.core.MineSuiteCorePlugin
version: ${project.version}
description: Suite for BungeeCord
author: Kekshaus
load: POSTWORLD
depend: [Vault, MineLib]
api-version: 1.13
commands:
  minesuite:
    description: Suit command
  mtools:
    description: Suit command
permissions:
    mineSuite.team:
        description: Alle User Permissions
        children:
            mineSuite.ban.team: true
            mineSuite.home.team: true
            mineSuite.warp.team: true
            mineSuite.teleport.team: true
            mineSuite.portal.team: true
            mineSuite.chat.team: true
            mineSuite.bypass: true
            mineSuite.ban.notifyinfo: true
            mineSuite.api.command: true
            mineSuite.tools.all: true
    mineSuite.user:
        description: Alle User Permissions
        children:
            mineSuite.ban.user: true
            mineSuite.home.user: true
            mineSuite.warp.user: true
            mineSuite.teleport.user: true
            mineSuite.portal.user: true
            mineSuite.chat.user: true
            mineSuite.api.command: true
    mineSuite.tools.all:
        description: Alle User Permissions
        children:
            mineSuite.tools.help: true
            mineSuite.tools.checkip: true
            mineSuite.tools.lastseen: true
            mineSuite.tools.debug: true
    mineSuite.bypass:
        description: Bypass permission
        default: op
    mineSuite.ban.notifyinfo:
        description: Baninfo permission
        default: op
    mineSuite.api.command:
        description: Baninfo permission
        default: op
    mineSuite.tools.help:
        description: Baninfo permission
        default: op
    mineSuite.tools.checkip:
        description: Baninfo permission
        default: op
    mineSuite.tools.lastseen:
        description: Baninfo permission
        default: op
    mineSuite.tools.debug:
        description: Baninfo permission
        default: op