name: MineSuiteCore
main : MineSuiteCore
version: ${project.version}
description: Suite for BungeeCord
author: Kekshaus
load: POSTWORLD
commands:
  minesuite:
    description: Suit command
permissions:
    mineSuite.team:
        description: Alle User Permissions
        children:
            mineSuite.ban.team: true
            mineSuite.home.team: true
            mineSuite.warp.team: true
            mineSuite.teleport.team: true
            mineSuite.portal.team: true
            mineSuite.chat.team: true
            mineSuite.guild.team: true
            mineSuite.bypass: true
            mineSuite.ban.notifyinfo: true
            mineSuite.api.command: true
    mineSuite.user:
        description: Alle User Permissions
        children:
            mineSuite.ban.user: true
            mineSuite.home.user: true
            mineSuite.warp.user: true
            mineSuite.teleport.user: true
            mineSuite.portal.user: true
            mineSuite.chat.user: true
            mineSuite.api.command: true
    mineSuite.bypass:
        description: Bypass permission
        default: op
    mineSuite.ban.notifyinfo:
        description: Baninfo permission
        default: op
    mineSuite.api.command:
        description: Baninfo permission
        default: op