name: XeonSuiteBukkit
main : de.nlinz.xeonSuite.bukkit.XeonSuiteBukkit
version: ${project.version}.b${build.number}
description: Suite for BungeeCord
author: Kekshaus
load: POSTWORLD
commands:
  xeonSuite:
    description: Suit command
permissions:
    xeonSuite.team:
        description: Alle User Permissions
        children:
            xeonSuite.ban.team: true
            xeonSuite.home.team: true
            xeonSuite.warp.team: true
            xeonSuite.teleport.team: true
            xeonSuite.portal.team: true
            xeonSuite.chat.team: true
            xeonSuite.guild.team: true
            xeonSuite.bypass: true
            xeonSuite.ban.notifyinfo: true
            xeonSuite.api.command: true
    xeonSuite.user:
        description: Alle User Permissions
        children:
            xeonSuite.ban.user: true
            xeonSuite.home.user: true
            xeonSuite.warp.user: true
            xeonSuite.teleport.user: true
            xeonSuite.portal.user: true
            xeonSuite.chat.user: true
            xeonSuite.api.command:: true

    xeonSuite.bypass:
        description: Bypass permission
        default: op
    xeonSuite.ban.notifyinfo:
        description: Baninfo permission
        default: op
    xeonSuite.api.command:
        description: Baninfo permission
        default: op